development:
  adapter: postgresql
  encoding: utf8
  database: audiomate_dev
  username: audiomate_user
  password: 
  host: localhost
test:
  adapter: postgresql
  encoding: utf8
  database: audiomate_test
  username: audiomate_user
  password: 
  host: localhost
production:
